import type { StudentData } from "@/components/student-card"

export const students: StudentData[] = [
  {
    id: "1",
    name: "Alex Johnson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    university: "MIT",
    course: "Computer Science",
    tags: ["programming", "python", "algorithms", "machine-learning"],
    rating: 4.9,
    reviewCount: 47,
    description: "Senior CS student specializing in algorithms and machine learning. I can help you understand complex concepts and ace your coding interviews.",
    pricePerHour: 45,
  },
  {
    id: "2",
    name: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    university: "Stanford",
    course: "Mathematics",
    tags: ["math", "calculus", "statistics", "linear-algebra"],
    rating: 5.0,
    reviewCount: 62,
    description: "Math tutor with 3 years of experience. I break down complex problems into simple, understandable steps.",
    pricePerHour: 40,
  },
  {
    id: "3",
    name: "Marcus Williams",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    university: "Harvard",
    course: "English Literature",
    tags: ["english", "writing", "essays", "literature"],
    rating: 4.8,
    reviewCount: 38,
    description: "Published writer and English major. I specialize in essay writing, creative writing, and literary analysis.",
    pricePerHour: 35,
  },
  {
    id: "4",
    name: "Emily Davis",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
    university: "UC Berkeley",
    course: "Data Science",
    tags: ["statistics", "r-programming", "data-analysis", "python"],
    rating: 4.7,
    reviewCount: 29,
    description: "Data science grad student. I can help with statistics, R programming, and data visualization projects.",
    pricePerHour: 50,
  },
  {
    id: "5",
    name: "James Kim",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    university: "Columbia",
    course: "Economics",
    tags: ["economics", "finance", "presentations", "excel"],
    rating: 4.6,
    reviewCount: 24,
    description: "Economics major with internship experience at top firms. Expert in presentations and financial modeling.",
    pricePerHour: 42,
  },
  {
    id: "6",
    name: "Lisa Thompson",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
    university: "Yale",
    course: "Biology",
    tags: ["biology", "chemistry", "exams", "pre-med"],
    rating: 4.9,
    reviewCount: 51,
    description: "Pre-med student with extensive tutoring experience. I specialize in MCAT prep and science courses.",
    pricePerHour: 55,
  },
  {
    id: "7",
    name: "Daniel Martinez",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    university: "Princeton",
    course: "Physics",
    tags: ["physics", "math", "calculus", "mechanics"],
    rating: 4.8,
    reviewCount: 33,
    description: "Physics PhD candidate. I love making complex physics concepts intuitive and accessible.",
    pricePerHour: 48,
  },
  {
    id: "8",
    name: "Rachel Green",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
    university: "NYU",
    course: "Psychology",
    tags: ["psychology", "research", "statistics", "writing"],
    rating: 4.7,
    reviewCount: 27,
    description: "Psychology graduate student specializing in research methods and statistical analysis.",
    pricePerHour: 38,
  },
]

export const categories = [
  { name: "Programming", icon: "💻", tag: "programming", count: 156 },
  { name: "Mathematics", icon: "📐", tag: "math", count: 142 },
  { name: "English", icon: "📝", tag: "english", count: 98 },
  { name: "Statistics", icon: "📊", tag: "statistics", count: 87 },
  { name: "Exam Prep", icon: "📚", tag: "exams", count: 124 },
  { name: "Presentations", icon: "🎯", tag: "presentations", count: 65 },
]

export const testimonials = [
  {
    id: "1",
    name: "Michael B.",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face",
    university: "UCLA",
    text: "Found an amazing tutor who helped me understand calculus concepts I&apos;d been struggling with for months. My grade went from C to A!",
    rating: 5,
  },
  {
    id: "2",
    name: "Jennifer L.",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face",
    university: "USC",
    text: "The peer tutoring approach made such a difference. My tutor explained Python in a way that actually made sense to me as a beginner.",
    rating: 5,
  },
  {
    id: "3",
    name: "David K.",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
    university: "Boston University",
    text: "Great platform for finding help with presentations and essays. The student I worked with gave me practical tips that improved my work immediately.",
    rating: 5,
  },
]

export const reviews = [
  {
    id: "1",
    studentName: "Michael B.",
    avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    date: "2 weeks ago",
    text: "Excellent tutor! Very patient and explains concepts clearly. Helped me understand algorithm complexity in a way that finally clicked.",
  },
  {
    id: "2",
    studentName: "Jennifer L.",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    date: "1 month ago",
    text: "Great session on Python basics. Covered a lot of ground and I feel much more confident tackling my assignments now.",
  },
  {
    id: "3",
    studentName: "David K.",
    avatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
    rating: 4,
    date: "1 month ago",
    text: "Very knowledgeable and helpful. Would recommend for anyone struggling with CS concepts.",
  },
  {
    id: "4",
    studentName: "Anna M.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
    rating: 5,
    date: "2 months ago",
    text: "Amazing experience! Helped me prepare for my technical interview and I got the internship!",
  },
]

export const conversations = [
  {
    id: "1",
    name: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    lastMessage: "Sure, I can help with that! Let&apos;s schedule a session.",
    timestamp: "2 min ago",
    unread: true,
  },
  {
    id: "2",
    name: "Alex Johnson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    lastMessage: "The algorithm session was great, thanks!",
    timestamp: "1 hour ago",
    unread: false,
  },
  {
    id: "3",
    name: "Marcus Williams",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    lastMessage: "I&apos;ll send you the essay feedback by tomorrow.",
    timestamp: "Yesterday",
    unread: false,
  },
  {
    id: "4",
    name: "Emily Davis",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    lastMessage: "Looking forward to our statistics session!",
    timestamp: "2 days ago",
    unread: false,
  },
]

export const messages = [
  {
    id: "1",
    senderId: "other",
    text: "Hi! I saw you need help with calculus. I&apos;d be happy to help!",
    timestamp: "10:30 AM",
  },
  {
    id: "2",
    senderId: "me",
    text: "Yes! I&apos;m struggling with integration techniques. Can you help?",
    timestamp: "10:32 AM",
  },
  {
    id: "3",
    senderId: "other",
    text: "Absolutely! I specialize in calculus. What specific topics are you having trouble with?",
    timestamp: "10:33 AM",
  },
  {
    id: "4",
    senderId: "me",
    text: "Mainly integration by parts and u-substitution. I have an exam next week.",
    timestamp: "10:35 AM",
  },
  {
    id: "5",
    senderId: "other",
    text: "Perfect, I can definitely help with those. Would you like to schedule a session this week?",
    timestamp: "10:36 AM",
  },
  {
    id: "6",
    senderId: "other",
    text: "I have availability tomorrow afternoon or Thursday morning.",
    timestamp: "10:36 AM",
  },
  {
    id: "7",
    senderId: "me",
    text: "Thursday morning works great for me! What time?",
    timestamp: "10:38 AM",
  },
  {
    id: "8",
    senderId: "other",
    text: "Sure, I can help with that! Let&apos;s schedule a session.",
    timestamp: "10:40 AM",
  },
]
